# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
Bundler/OrderedGems:
  Enabled: true
  TreatCommentsAsGroupSeparators: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
